[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[rpc_endpoints]
tempo_testnet = "https://rpc.testnet.tempo.xyz"

[etherscan]
tempo_testnet = { key = "", url = "https://scout.tempo.xyz/api/" }
